### ISSUE TITLE
Unrealistic design goal

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#1]
The spec says we want 128kbyte flash written in less than a second. This is not possible over 1Mbit can. If you assume 50% overhead, it takes at least two seconds. If we acknowledge each package like you proposed in the transport layer it's even worse.

**Comment by Stapelzeiger** [comment]
If we assume we have about 25 motor cards in the robot, it would take 50seconds to flash all cards.
Maybe broadcast would be an option?

**Comment by antoinealb** [comment]
Yes, agree that it is unrealistic, forgot to update this design goal.

I think 50 seconds to a minute to update the whole robot is pretty OK. I mean we should not do it too often, since the "intelligence" has moved on the Linux board. Plus we have unit testing and workbench (off-robot) testing that will also cut update frequency.

**Comment by antoinealb** [comment]
So I did some performance estimate and indeed one second was wayyy too optimistic... Could you check if it seems more reasonable to you now ?

**Comment by Stapelzeiger** [comment]
Yes, looks good. 1MB is probably larger than our average firmware. With 128k (which will be about the max size of the motor card fw) it would be around 2-3 seconds to flash.

**Comment by antoinealb** [comment]
Mmm, are you sure about 128k ? How much was the test firmware with UAVCAN?

**Comment by Stapelzeiger** [comment]
I think our new controllers have 128k or 256k.

**Comment by antoinealb** [comment]
But the binary was like 150 kB no ? Or was it 150 kb ?

**Comment by Stapelzeiger** [comment]
I just checked we're at 95'788bytes

**Comment by antoinealb** [comment]
:+1: Then it should be fast enough.
