### ISSUE TITLE
Memory copying and limitations

### ISSUE THREAD

**Issue by msplr** [cvra/can-bootloader#18]
For `command_write_flash()` the whole page data is copied from the datagram buffer to a separate page buffer by `cmp_read_bin()`. This works fine if the flash page size is only 2K, but we will run into memory problems with page sizes up to 128K like in the F4 controllers.
I propose we write the flash page directly from the datagram buffer by extracting the read pointer from the serializer.

**Comment by antoinealb** [comment]
Agree. It should be quite easy to do using existing APIs. Would you like me
to do it ? I have the time.

**Comment by msplr** [comment]
I suggest to change the argument to `serializer_t *` as a simple solution. How would you do it?
You can also make the changes if you want.

**Comment by antoinealb** [comment]
My suggestion (#19) is pretty ugly, but it requires no changes to existing API. Since zero copy operation will result in some uglyness either way, I suggest we go with that.

**Comment by msplr** [comment]
For the moment, I'm ok with that. We can rewrite it later.
