### ISSUE TITLE
UART version of bootloader protocol

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#2]
- The uart version of the protocol allows for easier testing, since we can write the sending part on a computer while testing the receiving node.
- An uart version is useful for other projects

**Comment by antoinealb** [comment]
For example it is useful if we want to flash the beacons via bluetooth ;)

**Comment by Stapelzeiger** [comment]
And I would use the same bootloader for my personal projects, so more testing!

**Comment by antoinealb** [comment]
Should I put the reason for an UART version in the proposal ?

**Comment by Stapelzeiger** [comment]
Ok

**Comment by antoinealb** [comment]
Done
