### ISSUE TITLE
Protocol versioning

### ISSUE THREAD

**Issue by msplr** [cvra/can-bootloader#24]
We should include versions in our bootloader protocol. 
Each datagram should first pass a compatibility check before it is processed.

**Comment by Stapelzeiger** [comment]
Agree.

**Comment by antoinealb** [comment]
We could use the three reserved bits in the id for that.

**Comment by Stapelzeiger** [comment]
Why would you put it in the CAN id?

**Comment by antoinealb** [comment]
To filter it using hardware. But it is probably more flexible to put it as a byte somewhere in the datagram.

**Comment by Stapelzeiger** [comment]
I'm for putting it in the datagram. I'd like to keep extensibility of the CAN layer, see also #25.

**Comment by antoinealb** [comment]
Ok.  1 byte is enough I would say ?

**Comment by msplr** [comment]
1 byte is ok.

**Comment by antoinealb** [comment]
Ok. I can implement it, but I would like to fix the unit tests first ;)

**Comment by antoinealb** [comment]
Where should this byte go ? I would say very first byte, do you agree ?
