### ISSUE TITLE
CAN ID allocation

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#25]
For extensibility we should make the following changes:
- the three "reserved bits" should be defined either as 0 or 1 for a valid bootloader frame
- the "reserved bits" should be first followed by the "first frame indicator" followed by the node id. This permits the use of the same addressing scheme (the first 4 bits are the data type, followed by 7bit node id) for other uses. (you usually want the data type to come before the node id for arbitration)

**Comment by msplr** [comment]
Fixed by #35
