### ISSUE TITLE
Dependency Tracking

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#30]
please add your dependencies as git submodules to track the version. (this includes the packager)

**Comment by antoinealb** [comment]
Ok for you if we do it just before release ? Otherwise there might be a long list of "update submodule XX" commits.

**Comment by Stapelzeiger** [comment]
As a general rule I think all dependencies should be tracked with an exact version. Otherwise it's not possible to checkout a past state. It's kind of like having untracked files for single repo projects. So I would add them as soon as possible. I have absolutely no problem with commits that update a lib / dependency.
