### ISSUE TITLE
Bootloader Command Set Version

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#34]
Add a version number for command set.

**Comment by Stapelzeiger** [comment]
I suggest versioning the entire command set instead of individual commands. (Commands for two different versions are always incompatible)
Rationale: this removes the complexity of having to deal with combinations of command versions.

**Comment by antoinealb** [comment]
Hmm ok for me. So simply some integer field before the command ID would be ok ?

I am going on holidays right now so I won't be able to do it before the 30th. I will do it at this moment, I don't feel like this is some urgent feature.
