### ISSUE TITLE
Simpler Flash commands to get around memory limitations.

### ISSUE THREAD

**Issue by msplr** [cvra/can-bootloader#37]
The problem from issue #18 with very large flash pages is still not solved.
In some controllers there is not enough continuous memory to contain the data a whole flash page and the command arguments. 
I propose to change the command set by separating the flash write command into two separate commands:
- flash page erase, argument: address of a flash page
- flash write, arguments: address and data to write. (doesn't need to be a whole page)

This change wouldn't complicate things as they are now, but it solves the problem by allowing to divide large pages into smaller pieces and write them separately.

**Comment by msplr** [comment]
I thought about a simpler alternative: just add a page erase flag to the flash write command, to indicate if the page has to be erased first.

**Comment by antoinealb** [comment]
A cleaner design would be to add a page erase command, no ?

**Comment by msplr** [comment]
Ok, though the code for page write and page erase will be almost the same.
But you're right, it should be done properly while changes are easy.
I'll make a pull request soon.

**Comment by antoinealb** [comment]
Closed in #38
