### ISSUE TITLE
CAN Transport layer

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#4]

**Comment by Stapelzeiger** [comment]
I think we can use a lot less ACKs since we don't expect to have a lot of errors on the can bus.
For example one ACK per correctly received page (maybe even with a checksum) would be enough.

**Comment by Stapelzeiger** [comment]
The sequence numbers are not necessary since we can guarantee to send packets in order and if the packet count / checksum doesn't match after one page, we know something went wrong.

**Comment by antoinealb** [comment]
Okay I rewrote the CAN transport layer to simplify it.

**Comment by Stapelzeiger** [comment]
We need some flag to indicate the first frame in a command.

**Comment by Stapelzeiger** [comment]
In CAN you should never send frames with the same can-identifier form different nodes without coordination. So we should better use the source node-id instead of the destination node-id for the can identifier.

**Comment by antoinealb** [comment]
> In CAN you should never send frames with the same can-identifier form different nodes without coordination. So we should better use the source node-id instead of the destination node-id for the can identifier.

For the answers to the host ?

**Comment by antoinealb** [comment]
> We need some flag to indicate the first frame in a command.

This is better handled at datagram level I think.

**Comment by Stapelzeiger** [comment]
> > We need some flag to indicate the first frame in a command.
> 
> This is better handled at datagram level I think.

This is what i meant. The fist datagram should have a flag set.

**Comment by Stapelzeiger** [comment]
> > In CAN you should never send frames with the same can-identifier form different nodes without coordination. So we should better use the source node-id instead of the destination node-id for the can identifier.
> 
> For the answers to the host ?

This is where the problem arises, but I suggest to use the source-id for all frames.

**Comment by antoinealb** [comment]
Well the first datagram starts with a START (0xC0) marker. Isn't that enough ?

For the CAN id, how would you handle adressing then ?

**Comment by Stapelzeiger** [comment]
> Well the first datagram starts with a START (0xC0) marker. Isn't that enough ?

Only if 0xC0 never appears at the fist byte for other datagrams

**Comment by Stapelzeiger** [comment]
> For the CAN id, how would you handle adressing then ?

with a field in the command
