### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by msplr** [cvra/can-bootloader#5]
Some ideas for additional features:
- firmware download mechanism.
- firmware check (perhaps on every boot before the application is started).

**Comment by antoinealb** [comment]
> firmware download mechanism.

You mean download the firmware from the board to the host ? Ok, we could add this, but I am not sure of the use case.

> firmware check (perhaps on every boot before the application is started).

Good idea. How would you implement it ? I added a command to compute the CRC of a flash region and write it to the bus, is that enough ?

**Comment by Stapelzeiger** [comment]
The most useful would be to have the bootloader store the checksum somewhere and check the app on boot. So that the app can be run automatically after a bootloader phase timeout.

**Comment by antoinealb** [comment]
Firmware download is in #16 and firmware check is in #17
