### ISSUE TITLE
Client bootloader flash timeout with big firmware.

### ISSUE THREAD

**Issue by msplr** [cvra/can-bootloader#53]
The client constantly times out in the firmware verify step when trying to flash a big firmware ~200K.
A longer timeout should be set for this step. (probably as a function of the binary length)

**Comment by antoinealb** [comment]
An alternative would be to change https://github.com/cvra/can-bootloader/blob/master/client/bootloader_flash.py#L99 to a `continue` statement, since the online boards are checked earlier. What do you think ?

**Comment by antoinealb** [comment]
Ah no, that would not work. Working on a fix now.

**Comment by antoinealb** [comment]
So I pushed a fix in #55. Can you try it and see if it fixes the bug in your use case ?
