### ISSUE TITLE
Redundant config pages

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/can-bootloader#8]
The config pages should be read only for the application. So there is no need to have redundant config pages. If a write fails we can just retry. If the config page is corrupt, the bootloader can just refuse to boot the application. This behavior is similar to the handling of a corrupt application binary.

The motivation is that flash-pages can be quite large on some controllers.

**Comment by antoinealb** [comment]
There is a need for redundant config page when changing bootloader configuration, such as Node ID or multicast groups. You don't want to loose your node ID when changing application CRC for example.

**Comment by Stapelzeiger** [comment]
how do you connect new devices without a config to the bus?

**Comment by antoinealb** [comment]
You have a default config, and the initial configuration is done out of robot, one board at a time.

**Comment by Stapelzeiger** [comment]
So if you accidentally change node ID to some already used ID, there is no way to recover?

**Comment by antoinealb** [comment]
I don't know if we should let the user change the node ID in robot.

**Comment by antoinealb** [comment]
After discussing the topic today, we could not find a solution to the Node ID problem. The two main approaches were : 
- Use a random NodeID, rely on human readable name.
- Program the NodeID when building the board and never change it.

For the rest of the config, we decided that the bootloader should provide an API for read-only configuration access. This would take the form of a function pointer returning the adress of the config data.

**Comment by antoinealb** [comment]
Discussed this today at Büro: we will attribute the Node IDs manually during manufacturing and write them on the board.
