### ISSUE TITLE
"can" module conflicts with PythonCAN; causes issues with UAVCAN

### ISSUE THREAD

**Issue by antoinealb** [cvra/can-bootloader#87]
The `can` package defined in this repository's python code is conflicting with PythonCAN. As the latter is used by PyUAVCAN, it means that we cannot have both this repository and PyUAVCAN installed in the same virtual environment. This is annoying as we rely on both to do our work at the club  :cry: 

The workaround I am currently using is to have a different virtual environment for the bootloader and for our UAVCAN tools, but I expect it to be quite confusing.

**Comment by gitgud187** [comment]
I'm facing the same problem using the same library - have you found a solution yet?

**Comment by antoinealb** [comment]
Sorry for not answering faster. In the end the approach that I took was to rename the conflicting module.

**Comment by gitgud187** [comment]
> Sorry for not answering faster. In the end the approach that I took was to rename the conflicting module.

No problem, I actually saw your commit like a day after you did it and it works perfectly, thanks very much for sharing your efforts.
